//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceRegistryWcfServiceLibrary.PeerDiagnosticServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PeerDiagnosticServiceReference.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IUserService/MethodThatWillChangeData")]
        void MethodThatWillChangeData(int value);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IUserService/MethodThatWillChangeData")]
        System.Threading.Tasks.Task MethodThatWillChangeDataAsync(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : ServiceRegistryWcfServiceLibrary.PeerDiagnosticServiceReference.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<ServiceRegistryWcfServiceLibrary.PeerDiagnosticServiceReference.IUserService>, ServiceRegistryWcfServiceLibrary.PeerDiagnosticServiceReference.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void MethodThatWillChangeData(int value) {
            base.Channel.MethodThatWillChangeData(value);
        }
        
        public System.Threading.Tasks.Task MethodThatWillChangeDataAsync(int value) {
            return base.Channel.MethodThatWillChangeDataAsync(value);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PeerDiagnosticServiceReference.ISubscription", CallbackContract=typeof(ServiceRegistryWcfServiceLibrary.PeerDiagnosticServiceReference.ISubscriptionCallback))]
    public interface ISubscription {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/INotifications/UpdateData")]
        void UpdateData(int newValue);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/INotifications/UpdateData")]
        System.Threading.Tasks.Task UpdateDataAsync(int newValue);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISubscription/Subscribe")]
        void Subscribe(string ServiceName);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISubscription/Subscribe")]
        System.Threading.Tasks.Task SubscribeAsync(string ServiceName);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISubscription/Unsubscribe")]
        void Unsubscribe(string ServiceName);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISubscription/Unsubscribe")]
        System.Threading.Tasks.Task UnsubscribeAsync(string ServiceName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISubscriptionCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISubscription/UpdateData")]
        void UpdateData(int newValue);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISubscriptionChannel : ServiceRegistryWcfServiceLibrary.PeerDiagnosticServiceReference.ISubscription, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubscriptionClient : System.ServiceModel.DuplexClientBase<ServiceRegistryWcfServiceLibrary.PeerDiagnosticServiceReference.ISubscription>, ServiceRegistryWcfServiceLibrary.PeerDiagnosticServiceReference.ISubscription {
        
        public SubscriptionClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public SubscriptionClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public SubscriptionClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public SubscriptionClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public SubscriptionClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void UpdateData(int newValue) {
            base.Channel.UpdateData(newValue);
        }
        
        public System.Threading.Tasks.Task UpdateDataAsync(int newValue) {
            return base.Channel.UpdateDataAsync(newValue);
        }
        
        public void Subscribe(string ServiceName) {
            base.Channel.Subscribe(ServiceName);
        }
        
        public System.Threading.Tasks.Task SubscribeAsync(string ServiceName) {
            return base.Channel.SubscribeAsync(ServiceName);
        }
        
        public void Unsubscribe(string ServiceName) {
            base.Channel.Unsubscribe(ServiceName);
        }
        
        public System.Threading.Tasks.Task UnsubscribeAsync(string ServiceName) {
            return base.Channel.UnsubscribeAsync(ServiceName);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PeerDiagnosticServiceReference.IDiagnostic")]
    public interface IDiagnostic {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiagnostic/Ping", ReplyAction="http://tempuri.org/IDiagnostic/PingResponse")]
        bool Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiagnostic/Ping", ReplyAction="http://tempuri.org/IDiagnostic/PingResponse")]
        System.Threading.Tasks.Task<bool> PingAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDiagnosticChannel : ServiceRegistryWcfServiceLibrary.PeerDiagnosticServiceReference.IDiagnostic, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DiagnosticClient : System.ServiceModel.ClientBase<ServiceRegistryWcfServiceLibrary.PeerDiagnosticServiceReference.IDiagnostic>, ServiceRegistryWcfServiceLibrary.PeerDiagnosticServiceReference.IDiagnostic {
        
        public DiagnosticClient() {
        }
        
        public DiagnosticClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DiagnosticClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiagnosticClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiagnosticClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Ping() {
            return base.Channel.Ping();
        }
        
        public System.Threading.Tasks.Task<bool> PingAsync() {
            return base.Channel.PingAsync();
        }
    }
}
